name: gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
      - name: Deploy Flutter web app to github pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: gh-pages
